# -*- coding: utf-8 -*-
"""Third concept bank (Task C, continued). Brings the bank to 90 concepts."""

from content.concepts import C

CONCEPTS_C = [

# ---------------------------------------------------------------- Networks
C("net_nat_private", "Computer Networks", "private addresses and NAT",
  [("Says private ranges are not routable on the public internet", "addresses like 192.168.x.x are not routed on the public internet"),
   ("Says NAT rewrites addresses at the boundary", "the router replaces the private source address with its public one"),
   ("Says the mapping is what lets replies return", "the router keeps a table of ports so replies find the right host"),
   ("Says inbound connections need explicit configuration", "an inside host is not reachable from outside without port forwarding")],
  "that a device with an address is on the internet, so any address can be reached from anywhere",
  "My laptop has an IP address, so my classmate should be able to connect to my server from her hostel using it.",
  ("Set up port forwarding on the router, because the firewall is blocking the connection.",
   "the action is right, but the obstacle is address translation rather than a firewall rule"),
  "NAT translates network addresses.",
  "IPv6 has a much larger address space.",
  "Give out the router's public address and forward a port to your machine, because your private address has no meaning outside your own network.",
  "Many hosts share one public address, so the router can only deliver an inbound packet if a mapping already exists for it.",
  "Print your local address, look up your public address, compare them, and then trace what your router rewrites on an outbound connection.",
  "Your address starts with 192.168. How many other networks in the country contain a machine with exactly that address?",
  "Ask whether the address you are handing out is unique in the world or only on your network.",
  "Private ranges exist so networks can be numbered without global coordination, and routers drop them on the public side. NAT makes them work anyway: on the way out, the router rewrites the source address to its public one and records the port mapping; replies are matched against that table and rewritten back. Outbound therefore just works and inbound does not, because no mapping exists until you create one - hence port forwarding, relays or tunnels for hosting a service from inside.",
  "Two devices behind the same router both want to host on port 8080. Say what breaks and what you would change.",
  [("lecture#net-w8-nat", "Week 8: address translation explains why outbound connections work and inbound ones need configuration."),
   ("lab#net-w8-brief", "Lab 8 brief: compare local and public addresses and document the router's mapping table.")],
  ("lecture#net-w8-2017", "Archived note: every device address is reachable from the internet."),
  ["private", "mapping", "forward", "public"]),

C("net_packet_switching", "Computer Networks", "packet switching",
  [("Says data is split into packets routed independently", "the message is divided into packets that can take different routes"),
   ("Says links are shared statistically rather than reserved", "no circuit is reserved, so capacity is shared between flows"),
   ("Says packets can arrive out of order or be lost", "reordering and loss are normal and handled above the network layer"),
   ("Contrasts with a reserved circuit", "a circuit guarantees capacity but wastes it when nobody is speaking")],
  "picturing a connection as a dedicated wire held open for you, which then makes loss and jitter look like faults",
  "When I open a connection the network reserves a path for it, so packets cannot arrive out of order or be dropped.",
  ("Buffer the video for a few seconds before playing, because the network is unreliable.",
   "the mitigation is right but 'unreliable' is vague - the buffer exists to absorb variable queueing delay"),
  "The internet uses packet switching.",
  "TCP is connection-oriented.",
  "Treat variation as the normal case: packets are forwarded hop by hop with no reservation, so ordering and loss recovery belong to the layer above.",
  "Statistical sharing means your packets queue behind other people's, and queue length changes, which is where jitter and loss come from.",
  "Send a steady stream and record per-packet arrival times over two minutes, then explain the spread rather than the average.",
  "Nobody reserved capacity for your download. What happens to your packet when a burst from another user arrives first?",
  "Think about what the router does with two packets arriving at once for the same outgoing link.",
  "Packet switching multiplexes many conversations onto shared links: each packet is forwarded independently, queued behind whatever else is present, and may be reordered or dropped when queues fill. That is the design, not a defect - it is what makes the network cheap and resilient, and it is why reliability, ordering and pacing are implemented at the ends rather than in the middle. Circuit switching reserves capacity and delivers predictability, at the cost of wasting the reservation whenever the source is idle.",
  "A lecture stream stutters at 8pm but not at 6am. Explain the mechanism and name one fix at each end.",
  [("lecture#net-w1-switching", "Week 1: packet switching shares links statistically; jitter and loss are consequences, not faults."),
   ("lab#net-w1-brief", "Lab 1 brief: record packet arrival times across the day and explain the variation.")],
  ("lecture#net-w1-2018", "Archived note: the network reserves a path for each connection."),
  ["queue", "independent", "jitter", "share"]),

C("net_wifi_medium", "Computer Networks", "shared wireless medium",
  [("Says wireless is a shared medium within a cell", "everyone on the access point shares the same airtime"),
   ("Says only one device transmits at a time per channel", "devices take turns, so throughput is divided rather than duplicated"),
   ("Says distance and interference lower the rate", "a weak or noisy link drops to a slower rate and uses more airtime"),
   ("Says a slow device slows the cell", "one distant device transmitting slowly consumes airtime everyone else needs")],
  "that each connected device gets its own share of a fixed advertised speed, as though the access point had a wire per user",
  "The access point is rated at 300 Mbps and there are 30 of us, so each person should get about 10 Mbps regardless of where they sit.",
  ("Move closer to the access point for a better connection, because signal strength matters.",
   "the advice works but the reason should be airtime: a stronger signal means a higher rate, so you finish sooner and free the channel"),
  "Wi-Fi is a shared medium.",
  "Use a wired connection for stability.",
  "Reason in airtime, not bandwidth per head: a weak client transmits slowly and occupies the channel that everyone else is waiting for.",
  "Only one transmission can succeed at a time in a cell, so the scarce resource is time on air, and low-rate clients consume disproportionate amounts of it.",
  "Measure your throughput alone and in a full lab, note the signal rate in each case, and explain the difference in airtime terms.",
  "Thirty laptops, one channel. What has to happen before your laptop can send its next frame?",
  "Count what is being divided. It is not megabits, it is milliseconds.",
  "A Wi-Fi cell is one shared channel: devices contend and transmit one at a time, so the advertised rate is a ceiling for the cell, not a per-user allocation. Rate adapts to link quality, and a distant client sending at a low rate holds the channel far longer per byte - which is why one weak device degrades everyone. Practical levers are airtime, not bandwidth: fewer retransmissions, closer clients, less broadcast chatter, and splitting users across bands or access points.",
  "A lab of 40 students runs a large download at once. Propose two changes and say which resource each frees.",
  [("lecture#net-w10-wireless", "Week 10: wireless capacity is analysed in airtime; rate adaptation is examinable."),
   ("lab#net-w10-brief", "Lab 10 brief: measure throughput in an empty and a busy lab and explain the gap.")],
  ("lecture#net-w10-2019", "Archived note: access point capacity is divided equally between connected devices."),
  ["airtime", "contend", "rate", "shared"]),

# ---------------------------------------------------------------- OS
C("os_scheduling", "Operating Systems", "CPU scheduling policies",
  [("Says the scheduler decides which ready process runs next", "the scheduler picks among ready processes when the CPU is free"),
   ("Describes round robin and its time slice", "round robin gives each process a fixed slice in turn"),
   ("Says priority scheduling can starve low-priority work", "a stream of high-priority jobs can starve the rest without ageing"),
   ("Says the metric chosen changes the best policy", "throughput, turnaround and response time are optimised by different policies")],
  "that there is one best scheduling policy, rather than policies optimising different measures for different workloads",
  "Shortest job first gives the best average waiting time, so a general-purpose operating system should always use it.",
  ("Use round robin for the interactive system, because it is fair.",
   "the policy fits, but the reason that matters is bounded response time for interactive work, not fairness in the abstract"),
  "Schedulers decide what runs next.",
  "Processes have their own memory space.",
  "Name the metric first - response time for interactive work, turnaround for batch - then pick the policy that optimises it and say what it costs.",
  "Shortest job first needs to know job lengths in advance and can starve long jobs, which is why interactive systems trade average waiting time for a bounded slice.",
  "Simulate four jobs under round robin and shortest job first, compute average waiting and worst-case response for both, and say which workload each suits.",
  "A text editor and a video encoder are both ready. Which measure does the user of each one care about?",
  "Decide what you are optimising before you choose. The policies differ in what they are good at, not in quality.",
  "Scheduling is a trade, not a ranking. Shortest job first minimises average waiting time but needs job lengths and starves long jobs. Round robin bounds response time with a time slice, which is what interactive use needs, at some cost in average turnaround and context-switch overhead. Priority schemes serve importance but require ageing to avoid starvation. Real systems combine them in multi-level queues, because the workload is mixed.",
  "Your time slice is 200 ms and users report sluggish typing. Say what you would change and what regresses as a result.",
  [("lecture#os-w4-scheduling", "Week 4: policies are compared against a named metric; starvation must be addressed."),
   ("lab#os-w4-brief", "Lab 4 brief: simulate the supplied job set under two policies and report both metrics.")],
  ("lecture#os-w4-2018", "Archived note: shortest job first is the optimal scheduling policy."),
  ["metric", "slice", "starvation", "response"]),

C("os_file_permissions", "Operating Systems", "file permissions",
  [("Says permissions apply to owner, group and others", "each file has permissions for its owner, its group and everyone else"),
   ("Explains read, write and execute for files", "read allows viewing, write allows changing, execute allows running"),
   ("Says execute on a directory means traversal", "on a directory, execute permits entering it rather than running it"),
   ("Says wide permissions are a security decision, not a fix", "making a file world-writable removes the protection instead of fixing the access problem")],
  "that permission problems are obstacles to be cleared by widening access until the error stops",
  "The web server could not read the file, so I gave it 777 permissions and it works now.",
  ("Put the web server user in the group that owns the files, because groups exist for shared access.",
   "the fix is the right one, but the reason should be least privilege: it grants exactly the access needed and nothing wider"),
  "Permissions control who can access a file.",
  "Use a firewall to protect the server.",
  "Grant the narrowest thing that works - usually group membership plus read - instead of widening the file to everyone.",
  "Each permission bit is an authorisation granted to a set of principals, so widening to others authorises every account on the machine, including any that gets compromised.",
  "List the permissions on the failing path and on each parent directory, then grant the minimum that makes the read succeed and re-test.",
  "You set 777. Which accounts on that machine can now write that file?",
  "Ask who the permission is granted to, not whether the error went away.",
  "Permissions answer 'which principal may do what': owner, group, others, each with read, write and execute - and on a directory, execute means the right to traverse into it, which is why an unreadable parent breaks access to a readable file. Widening to 777 does make the error stop, and it authorises every local account and every process running as them. The professional move is the narrowest grant that works: correct ownership, group membership, read where read is needed.",
  "A log directory must be writable by one service and readable by two people. Propose the ownership and mode and defend it.",
  [("lecture#os-w9-security", "Week 9: permission changes must be justified by least privilege; 777 is not accepted in submissions."),
   ("lab#os-w9-brief", "Lab 9 brief: fix a permission failure with the narrowest change and document each step.")],
  ("lecture#os-w9-2017", "Archived note: use 777 when a service cannot read a file."),
  ["least privilege", "group", "traverse", "owner"]),

C("os_race_conditions", "Operating Systems", "race conditions and atomicity",
  [("Says a race is an outcome that depends on timing", "the result changes depending on how the operations interleave"),
   ("Says read-modify-write is not atomic by default", "incrementing a shared counter is three steps that can interleave"),
   ("Names a remedy", "a lock, an atomic operation or a single-owner design removes the interleaving"),
   ("Says tests may pass while the bug remains", "a race can hide for thousands of runs and appear under load")],
  "that a bug which does not reproduce is not a real bug, so passing tests mean the concurrency is correct",
  "It only failed once in a thousand runs and we cannot reproduce it, so there is nothing to fix.",
  ("Add a lock around the counter update, because shared data needs locking.",
   "the fix is correct, but stated as a rule it does not identify which sequence of steps was unsafe"),
  "Race conditions happen in concurrent programs.",
  "Threads share memory within a process.",
  "Make the update indivisible - a lock or an atomic operation - because the failure is a legal interleaving, not a random event.",
  "An increment is read, add, write; two threads can both read the old value and both write the same new one, so one update disappears.",
  "Run your unsynchronised counter 1,000 times with two threads, plot the distribution of final values, then repeat with a lock.",
  "Two threads read the counter as 41 at the same instant. What does each write back?",
  "Write the three machine steps of your one-line increment, then interleave two copies of them on paper.",
  "A race condition is not randomness; it is a set of legal interleavings, some of which are wrong. The classic is read-modify-write: two threads read the same value, both compute the same successor, and one update is lost. Reproducibility is a red herring - the interleaving is rare under test load and common under production load. Fixes remove the interleaving: a mutex around the critical section, an atomic operation, or a design where one owner mutates the state and others send it messages.",
  "Two handlers both check a seat is free and then book it. Describe the interleaving that oversells and the narrowest fix.",
  [("lecture#os-w7-races", "Week 7: concurrency answers must identify the unsafe interleaving before proposing a remedy."),
   ("lab#os-w7-brief", "Lab 7 brief: reproduce a lost update statistically and remove it.")],
  ("lecture#os-w7-2019", "Archived note: an error that cannot be reproduced can be ignored."),
  ["interleav", "atomic", "critical section", "lost update"]),

# ---------------------------------------------------------------- Security
C("sec_least_privilege", "Information Security", "least privilege",
  [("Says each account gets only the access its job requires", "an account should hold only the permissions its task needs"),
   ("Says privileges should be temporary where possible", "elevated access should be granted for a task and then withdrawn"),
   ("Says least privilege limits blast radius", "a compromised account can only reach what it was allowed to reach"),
   ("Says shared admin accounts defeat attribution", "if everyone uses one admin login, nobody can tell who did what")],
  "that privilege is about trusting people, so trustworthy colleagues can safely hold full access",
  "Everyone on the team is trustworthy, so giving all of us database admin rights is not a security problem.",
  ("Give the reporting service a read-only database user, because reports only read data.",
   "the grant is right but the argument should include the failure case: a compromised or buggy service then cannot write"),
  "Least privilege means minimum access.",
  "Use strong passwords for admin accounts.",
  "Scope each account to its task and make elevation temporary, because the control is about what a compromised session can reach, not about who deserves trust.",
  "Accounts are compromised far more often than people are dishonest, so the question is what an attacker inherits when they take over that session.",
  "List every account your project uses, the permissions each holds, and the one task it exists for, then remove every grant that has no task.",
  "Your account is phished tonight. What can the attacker reach with it, and what would you wish you had removed?",
  "Stop reasoning about the person and reason about the session after it is stolen.",
  "Least privilege is not a comment on colleagues. Credentials leak, machines get malware, and sessions get hijacked, so the design question is what an attacker inherits. Scope each account and service to the operations it actually performs, make elevation time-bound and logged, and give humans individual accounts so actions are attributable. The immediate payoff is a smaller blast radius; the second one is that you can answer 'who changed this?'",
  "Your deployment script needs occasional schema changes. Design the access so routine runs cannot alter the schema.",
  [("lecture#infosec-w11-access", "Week 11: access designs are marked on scope and on what a compromised credential reaches."),
   ("lab#infosec-w11-brief", "Lab 11 brief: enumerate the project's accounts and reduce each to the minimum working grant.")],
  ("lecture#infosec-w11-2018", "Archived note: grant full access to trusted team members for convenience."),
  ["scope", "blast radius", "temporary", "attribution"]),

C("sec_backups", "Information Security", "backups and recovery",
  [("Says a backup is only real if a restore has been tested", "an untested backup is an assumption, not a backup"),
   ("Says copies must be separated from the original", "a copy on the same machine dies with the machine"),
   ("Says at least one copy should be offline or immutable", "ransomware encrypts everything it can reach, including attached drives"),
   ("Says versions matter, not just the latest copy", "silent corruption needs older versions to recover from")],
  "treating backup as a copying task that is complete when the copy exists, rather than a recovery capability that has to be proved",
  "We sync the project folder to a connected external drive every night, so we are fully protected.",
  ("Keep a copy in cloud storage as well, because off-site copies are best practice.",
   "the extra copy helps, but the stated reason misses that a synced copy propagates deletion and encryption"),
  "You should back up your data.",
  "Use version control for source code.",
  "Add an offline or versioned copy and test a restore, because a synced attached drive inherits every deletion and every encryption.",
  "Sync propagates changes, including destructive ones, so a mirrored copy fails exactly in the scenarios that matter.",
  "Restore last week's version of one file from your backup, time how long it takes, and note anything you could not recover.",
  "Ransomware runs on your laptop tonight and encrypts every writable path. Which of your copies survives?",
  "Ask which failures each copy survives: disk death, theft, deletion, encryption, silent corruption.",
  "Backups are judged by restores. A nightly sync to an attached drive survives disk failure and nothing else: deletion, corruption and ransomware all propagate. The standard shape is three copies, two media, one off-site, with at least one offline or immutable and with retained versions so you can go back past the moment corruption started. And the test is not the backup log - it is restoring a real file and timing it.",
  "Your team keeps code on a hosting service and data on one laptop. Say what is actually protected and what is not.",
  [("lecture#infosec-w13-resilience", "Week 13: recovery claims must name the failure modes covered and the restore test performed."),
   ("lab#infosec-w13-brief", "Lab 13 brief: restore a file from your backup and document the steps and the time taken.")],
  ("lecture#infosec-w13-2017", "Archived note: a nightly sync to an attached drive is sufficient protection."),
  ["restore", "offline", "versions", "propagate"]),

C("sec_xss_encoding", "Information Security", "cross-site scripting and output encoding",
  [("Says untrusted data rendered into a page can execute", "user content placed into HTML can run as script"),
   ("Says the fix is contextual output encoding", "escape the data for the context it is rendered into"),
   ("Says input filtering alone is insufficient", "a blocklist of tags misses encodings and new vectors"),
   ("Names a defence-in-depth measure", "a content security policy limits what injected script can do")],
  "treating injection as dirty data to be scrubbed on the way in, rather than as data being interpreted as code on the way out",
  "I strip script tags from the comment when it is submitted, so the page is safe to render as HTML.",
  ("Use the template engine's automatic escaping, because frameworks handle security.",
   "the mechanism is right but the reason is that escaping is applied per output context, not that frameworks are trustworthy"),
  "XSS lets attackers run scripts.",
  "Use HTTPS to protect the page.",
  "Encode on output, for the context you are writing into - HTML body, attribute, URL or script - rather than sanitising at input.",
  "The same stored value is safe in one context and dangerous in another, so the only place with enough information to escape correctly is the moment of rendering.",
  "Store a comment containing a script tag, render it in three contexts, and show which encoding makes each safe.",
  "Your filter removed the script tag. What about an event handler attribute on an image tag?",
  "Ask where the value is interpreted, not where it entered.",
  "Injection is an interpretation problem. The stored comment is just text; danger appears when it is written into a page and parsed as HTML, an attribute, a URL or JavaScript - each needing different escaping. That is why output encoding, applied by the template engine at render time, is the primary control and input filtering is a weak supplement. Add a content security policy so that anything that slips through has a much smaller effect.",
  "A profile field is rendered inside a link's href. Say which encoding applies and what an attacker would otherwise inject.",
  [("lecture#infosec-w12-web", "Week 12: escaping is assessed per output context; blocklists earn no marks."),
   ("lab#infosec-w12-brief", "Lab 12 brief: exploit the vulnerable comment page, then fix it with contextual encoding.")],
  ("lecture#infosec-w12-2018", "Archived note: stripping script tags on input prevents cross-site scripting."),
  ["output", "context", "escape", "policy"]),

# ---------------------------------------------------------------- Web
C("web_caching", "Web Application Development", "caching and invalidation",
  [("Says a cache stores a copy to avoid repeating work", "the cache keeps a previous result so the work is not redone"),
   ("Says stale data is the cost of caching", "cached copies can be out of date after the source changes"),
   ("Names an invalidation strategy", "use a time to live, or invalidate the entry when the data changes"),
   ("Says cache keys must capture what varies", "the key has to include anything that changes the result, such as the user or the language")],
  "that caching is a performance switch with no semantics, so adding it cannot change what users see",
  "I added a cache in front of the dashboard and it is much faster, so the only effect is speed.",
  ("Add the user id to the cache key, because keys should be unique.",
   "the change is correct but the reason is that the response varies per user, which is a correctness issue, not uniqueness hygiene"),
  "Caching improves performance.",
  "Use a CDN for static assets.",
  "Decide the staleness you can tolerate and the key that captures what varies, then choose the invalidation rule to match.",
  "A cache answers with an old computation, so correctness now depends on when entries expire and on whether the key distinguishes the requests that should differ.",
  "Cache one endpoint, change the underlying data, and record how long the old value is served and to whom.",
  "Two students load the dashboard within a second of each other. What decides whether they see the same numbers?",
  "State how stale the answer may be, and what makes two requests different. Those two answers define your cache.",
  "Caching trades freshness for work. Two decisions define it: the key, which must include everything that changes the response - user, role, language, parameters - or you will serve one person's data to another; and invalidation, either a time to live you can defend or explicit eviction when the source changes. Measure the hit rate afterwards, because a cache with a poor key is a memory leak with extra steps.",
  "A price changes and customers see the old one for ten minutes. Say which choice caused that and what you would change.",
  [("lecture#web-w11-performance", "Week 11: caching answers must state the key and the invalidation rule."),
   ("lab#web-w11-brief", "Lab 11 brief: cache one endpoint, then demonstrate and bound the staleness you introduced.")],
  ("lecture#web-w11-2019", "Archived note: caching affects speed only."),
  ["key", "stale", "invalidate", "vary"]),

C("web_rest_idempotency", "Web Application Development", "HTTP methods and idempotency",
  [("Says GET is safe and must not change state", "a GET should not modify anything on the server"),
   ("Says PUT and DELETE are idempotent", "repeating the same PUT or DELETE leaves the same result"),
   ("Says POST is neither safe nor idempotent", "repeating a POST can create a second resource"),
   ("Says the semantics matter to caches, proxies and retries", "clients, proxies and crawlers retry or cache based on those properties")],
  "treating the method as a label chosen by convention, when infrastructure acts on its meaning",
  "We use POST for everything including the search page, since the method is just a naming convention.",
  ("Change the delete link to a POST, because links should not delete things.",
   "the instinct is right but the reason is that GET must be safe, since crawlers and prefetchers follow links"),
  "REST uses HTTP methods.",
  "Return 404 when a resource is missing.",
  "Match the method to the semantics - safe for reads, idempotent for replaceable updates - because browsers, proxies and crawlers act on those guarantees.",
  "Anything that follows links will issue GETs on its own, so a state change behind a GET will eventually be triggered by something that never intended it.",
  "Put a state change behind a GET in a test app, run a link prefetcher over it, and record what happened.",
  "A search engine crawls your admin page and follows every link. Which of your endpoints just ran?",
  "Ask which of your endpoints something else might call without a human deciding to.",
  "HTTP methods carry guarantees other software relies on. GET is safe: crawlers, prefetchers and browsers issue it freely, so state changes behind it get triggered by accident. PUT and DELETE are idempotent, so a client that times out can retry safely. POST is neither, which is why duplicate submissions need an idempotency key. Choosing methods by their semantics is what makes retries, caching and proxies behave rather than corrupt data.",
  "A mobile client retries after a timeout on an order endpoint. Say which method you would expose and what makes the retry safe.",
  [("lecture#web-w6-http", "Week 6: method choice is marked on safety and idempotency, not on style."),
   ("lab#web-w6-brief", "Lab 6 brief: audit your endpoints and correct any state change reachable by GET.")],
  ("lecture#web-w6-2017", "Archived note: the HTTP method is a naming convention."),
  ["safe", "idempotent", "retry", "crawler"]),

C("web_accessibility", "Web Application Development", "accessible markup",
  [("Says semantic elements convey structure to assistive technology", "headings, lists and landmarks let a screen reader navigate"),
   ("Says images need alternative text describing purpose", "alt text should say what the image conveys, not that it is an image"),
   ("Says colour alone must not carry meaning", "information shown only by colour is lost to some users"),
   ("Says keyboard operation must work", "everything usable with a mouse must be reachable with the keyboard")],
  "that accessibility is an appearance setting added at the end, rather than structure that has to be in the markup from the start",
  "We will add accessibility at the end by increasing the font size and improving the colours.",
  ("Use heading elements instead of styled divs, because that is cleaner markup.",
   "tidiness is a side benefit; the reason is that headings are how a screen-reader user navigates the page"),
  "Websites should be accessible.",
  "Use a responsive grid for layout.",
  "Put the structure in the markup - headings, labels, landmarks, alt text - because assistive technology reads structure, not appearance.",
  "A screen reader builds its navigation from the element tree, so a visually obvious heading that is a styled div does not exist as a heading at all.",
  "Navigate your page with the keyboard only and with a screen reader's heading list, and write down everything you could not reach or identify.",
  "Close your eyes and ask how you would jump to the third section of your page. What in your markup makes that possible?",
  "Test with the keyboard first; it exposes most structural problems in two minutes.",
  "Accessibility is structural. Assistive technology consumes the element tree: headings give a navigable outline, labels bind text to inputs, landmarks let a user skip to main content, alt text conveys what an image means. None of that is visible styling, which is why it cannot be bolted on at the end by adjusting colours. The quickest honest test is keyboard-only operation plus a heading list; both take minutes and catch most of it.",
  "Your form shows errors in red text beside the field. Say what a screen-reader user misses and how you would fix it.",
  [("lecture#web-w12-a11y", "Week 12: accessibility is assessed on markup structure, keyboard operation and text alternatives."),
   ("lab#web-w12-brief", "Lab 12 brief: navigate your project with the keyboard alone and fix every trap you find.")],
  ("lecture#web-w12-2018", "Archived note: accessibility is a styling concern addressed at the end of a project."),
  ["semantic", "keyboard", "alt", "structure"]),

# ---------------------------------------------------------------- Mobile
C("mob_dp_px", "Mobile Computing", "density-independent layout",
  [("Says physical pixels differ per device density", "two phones of the same size can have very different pixel counts"),
   ("Says layout units are density independent", "density-independent units keep physical size consistent across screens"),
   ("Says the system scales assets by density bucket", "the platform picks an asset for the device's density"),
   ("Says touch targets have a minimum physical size", "a tappable control needs a minimum physical size regardless of resolution")],
  "that a pixel is a fixed physical size, so a layout that looks right on one phone is right everywhere",
  "I set the button to 48 pixels because it looked right on my phone, so it will be the same size on every device.",
  ("Use density-independent units for the layout, because the guidelines recommend them.",
   "the unit is right but the reason is physical consistency across densities, which is also why touch targets are specified that way"),
  "Screens have different resolutions.",
  "Test on more than one device.",
  "Specify sizes in density-independent units and supply assets per density bucket, so the control keeps its physical size on every screen.",
  "The system multiplies density-independent units by the device's scale factor, which is exactly what keeps a 48-unit target the same physical size on a dense and a sparse screen.",
  "Render your layout on two emulated densities, measure the button in millimetres on each, and correct whichever one is under the minimum.",
  "Your button is 48 physical pixels. How wide is it in millimetres on a screen with three times the pixel density?",
  "Convert to physical size, not pixel count. That is what a thumb interacts with.",
  "Physical pixels are not a unit of size; density is what turns them into millimetres. Layout therefore uses density-independent units, which the system multiplies by the device scale factor, and bitmap assets are supplied per density bucket so they are not upscaled into blur. Touch targets are specified physically for a reason - a thumb does not shrink on a denser screen - so a control that is comfortable on your device can be unusable on another if you specified it in raw pixels.",
  "An icon looks sharp on your phone and blurry on a tablet. Explain the cause and the asset change you would make.",
  [("lecture#mob-w3-layout", "Week 3: layout answers must use density-independent units and justify touch target sizes."),
   ("lab#mob-w3-brief", "Lab 3 brief: run the same layout at two densities and report the measured control sizes.")],
  ("lecture#mob-w3-2017", "Archived note: specify sizes in physical pixels for precision."),
  ["density", "scale", "target", "asset"]),

C("mob_permissions", "Mobile Computing", "runtime permissions",
  [("Says sensitive access requires explicit user consent", "the user must grant access to things like location or contacts"),
   ("Says permission can be denied or revoked at any time", "the app must keep working when permission is refused or withdrawn"),
   ("Says the request should be in context", "ask at the moment the feature is used, with a reason"),
   ("Says you request only what the feature needs", "do not request permissions the app does not currently use")],
  "that permissions are a start-up formality, so the app can assume access once it has asked",
  "We request all permissions when the app first launches, so afterwards the features can just use them.",
  ("Ask for location only when the map screen opens, because users dislike permission prompts.",
   "the timing is right but the reason is comprehension and revocability, not just annoyance"),
  "Apps need permission for sensitive data.",
  "Store user data securely.",
  "Request each permission at the point of use with a reason, and write the denied path as a real feature rather than an error.",
  "Permission state can change between launches and mid-session, so every access has to be guarded rather than assumed from an earlier grant.",
  "Deny each permission your app requests, use every affected screen, and record where it crashes or silently does nothing.",
  "A user grants location, then revokes it in settings a week later. What does your next location call return?",
  "Write the denied branch first. If it does not exist, the feature is not finished.",
  "Runtime permissions are revocable state, not a one-time gate. Ask at the moment the feature needs the data, with a sentence explaining why, because a prompt with context is both more likely to be granted and more honest. Then handle refusal as a designed path: a manual entry field instead of location, an import option instead of contacts. Guard every access, since the grant can be withdrawn between sessions or mid-session.",
  "Your attendance app needs location once per class. Describe the request flow and what happens when the student refuses.",
  [("lecture#mob-w7-permissions", "Week 7: permission flows are marked on timing, justification and the denied path."),
   ("lab#mob-w7-brief", "Lab 7 brief: run your app with every permission denied and fix each failure.")],
  ("lecture#mob-w7-2018", "Archived note: request all permissions at first launch."),
  ["runtime", "revoke", "context", "denied path"]),

# ---------------------------------------------------------------- E-commerce
C("ecom_funnel_metrics", "Introduction to E-Commerce", "measuring cart abandonment",
  [("Defines the metric precisely", "abandonment is carts created that do not reach a completed order, over a stated period"),
   ("Says the denominator must be stated", "the rate depends on whether you count sessions, carts or users"),
   ("Says the stage of loss must be identified", "you need to know whether people leave at delivery cost, at sign-in or at payment"),
   ("Says a rate alone does not give a cause", "the number tells you where to look, not why people left")],
  "treating a headline rate as a diagnosis, so the response is chosen before the loss point is known",
  "Our cart abandonment is 70 percent, so we should add a discount code to the checkout page.",
  ("Instrument each checkout step before changing anything, because you need data first.",
   "the sequence is right but the reason should be that the remedy differs per stage - delivery cost, account creation and payment failure need different fixes"),
  "Cart abandonment is when customers do not complete the purchase.",
  "Send reminder emails to customers.",
  "Define the denominator, instrument each step, and find the stage where people leave before choosing a remedy.",
  "A single rate aggregates several different failures, and each stage has a different cheapest fix, so acting on the aggregate is guessing.",
  "Instrument the four checkout steps for one week, compute the drop between each pair, and name the largest single loss.",
  "Of the people who left, how many saw the delivery cost and how many never reached it?",
  "Break the funnel into steps and count the losses between them before proposing anything.",
  "A funnel number is only interpretable with its denominator and its stages. Carts per session, per user and per created cart give different figures, and an aggregate hides where the loss happens: surprise delivery cost at step two is a different problem from a failed payment at step four, and they have different fixes. Instrument the steps, find the largest drop, then form a hypothesis and test one change against it.",
  "Losses concentrate between delivery details and payment. Give two plausible causes and the measurement that distinguishes them.",
  [("lecture#ecom-w9-analytics", "Week 9: metric answers must state the denominator and the stage before proposing an action."),
   ("case#ecom-w9-funnel", "Class case: a shop's checkout is instrumented at four steps; most of the loss sits at the delivery cost screen.")],
  ("lecture#ecom-w9-2018", "Archived note: a high abandonment rate means the price is too high."),
  ["denominator", "stage", "instrument", "cause"]),

C("ecom_overselling", "Introduction to E-Commerce", "inventory and overselling",
  [("Says stock must be decremented atomically with the order", "the stock check and the decrement must happen as one indivisible step"),
   ("Says concurrent checkouts cause overselling", "two customers can both pass the check before either decrement is written"),
   ("Names a mechanism", "a conditional update, a reservation with a timeout, or row-level locking"),
   ("Says oversells need a business policy too", "you still need a rule for what happens when it occurs")],
  "that checking stock before charging is sufficient, because the two steps look adjacent in the code",
  "The code checks stock is greater than zero before taking payment, so we cannot sell the same item twice.",
  ("Reserve the item for ten minutes at checkout, because that is what large retailers do.",
   "the pattern fits, but the reason is that reservation makes the decrement atomic with the customer's intent, not that others do it"),
  "Stock should be reduced when an order is placed.",
  "Use a payment gateway for card processing.",
  "Make the check and the decrement one atomic operation - a conditional update that fails when stock is gone - and add a reservation window if payment takes time.",
  "Two requests can interleave between the check and the write, so both see stock available and both proceed; only atomicity closes that window.",
  "Fire twenty concurrent checkouts against one unit of stock in a test environment, count how many succeed, then apply the conditional update and repeat.",
  "Two customers press pay in the same second on the last unit. Where exactly does your code let both through?",
  "Mark the line where the check happens and the line where the decrement happens. Everything between them is the bug.",
  "Overselling is a race condition with money attached. The check and the decrement must be indivisible: an UPDATE ... SET stock = stock - 1 WHERE stock > 0 that reports zero affected rows is the simplest correct form, and reservations with expiry handle the case where payment takes time. Beyond the mechanism you need a policy - refund, substitute, backorder - because at scale you will still oversell occasionally through returns and reconciliation delays.",
  "Payment takes up to 90 seconds with a mobile money confirmation. Design the stock handling for that window.",
  [("lecture#ecom-w10-inventory", "Week 10: inventory answers must show the atomic operation and state the oversell policy."),
   ("lab#ecom-w10-brief", "Lab 10 brief: reproduce an oversell with concurrent requests and eliminate it.")],
  ("lecture#ecom-w10-2017", "Archived note: checking stock before payment prevents overselling."),
  ["atomic", "conditional", "reserve", "concurrent"]),

# ---------------------------------------------------------------- Multimedia
C("mm_frame_rate", "Introduction to Multimedia", "frame rate and resolution",
  [("Says frame rate is frames per second and resolution is pixels per frame", "frame rate counts frames per second, resolution counts pixels in each frame"),
   ("Says they trade against a fixed bitrate", "at a fixed bitrate, more pixels or more frames means fewer bits for each"),
   ("Matches the choice to content", "motion needs frame rate, fine detail needs resolution"),
   ("Says the delivery constraint should drive the setting", "choose the setting your audience's connection can actually carry")],
  "that quality is a single dial, so raising every setting always produces a better video",
  "I exported at the highest resolution and the highest frame rate, so the video is the best quality possible for our viewers.",
  ("Export at 720p for the campus audience, because most phones are 720p.",
   "the setting is reasonable but the reason should be the delivery bitrate your viewers can sustain"),
  "Higher resolution means better quality.",
  "Use a tripod for stable footage.",
  "Pick frame rate and resolution against your bitrate budget and content type, since at a fixed bitrate they compete for the same bits.",
  "An encoder spreads a fixed bit budget over pixels and frames, so raising both without raising bitrate makes every frame worse.",
  "Encode the same clip three ways within one bitrate budget, watch them on a phone, and say which trade suited the content.",
  "Your bitrate is fixed. What happens to the bits per pixel when you double the frame rate?",
  "Write the budget as bits per second, then divide it by pixels and frames.",
  "Resolution and frame rate both consume the same bit budget. At a fixed bitrate, doubling either halves the bits available to each unit, so an over-specified export looks worse than a modest one - blockier motion, mushy detail. Choose by content and delivery: talking heads and slides favour resolution and lower frame rate; sport and screen motion favour frame rate; and the ceiling is what your audience's connection sustains, not what your editor can export.",
  "A lecture recording is mostly static slides with occasional writing. Propose settings and justify each against the content.",
  [("lecture#mm-w9-video", "Week 9: export settings must be justified against a bitrate budget and the delivery context."),
   ("lab#mm-w9-brief", "Lab 9 brief: encode one clip three ways within a fixed bitrate and compare the results.")],
  ("lecture#mm-w9-2018", "Archived note: always export at the maximum available settings."),
  ["bitrate", "budget", "motion", "trade"]),

C("mm_contrast", "Introduction to Multimedia", "colour contrast and legibility",
  [("Says contrast is a ratio between text and background luminance", "contrast is measured as a ratio between the two luminances"),
   ("Says there is a minimum ratio for body text", "body text needs a defined minimum ratio to be readable"),
   ("Says colour alone should not carry meaning", "meaning shown only in colour is lost to colour-blind users and in print"),
   ("Says the check is measured, not judged by eye", "use a contrast checker rather than trusting how it looks on your screen")],
  "that legibility is a matter of taste judged on your own screen, rather than a measurable ratio with a threshold",
  "The grey text on the white background looks fine on my laptop, so the slides are readable.",
  ("Darken the body text, because light grey looks washed out.",
   "the change is right but the justification is aesthetic, when the case is a measured ratio and a threshold"),
  "Slides should be readable.",
  "Use a consistent font across the deck.",
  "Measure the ratio with a checker and raise it past the threshold, and encode any colour-coded meaning a second way.",
  "Perceived contrast depends on the display, the ambient light and the viewer's vision, so a measured luminance ratio is the only portable criterion.",
  "Run your three slide colour pairs through a contrast checker, record each ratio, and fix the ones below the threshold.",
  "Your slide will be projected in a bright room from a dim projector. What happens to the grey on white?",
  "Measure the pair rather than judging it. One number settles the argument.",
  "Contrast is a luminance ratio with published thresholds, and it is measurable precisely because judgement by eye is unreliable - your laptop is brighter, closer and cleaner than the lecture projector. Run the pairs through a checker and fix what falls short. Separately, never let colour be the only carrier of meaning: add a label, a shape or a pattern, so the slide survives colour blindness, greyscale printing and a washed-out projector.",
  "A chart distinguishes three lines by colour only. Give two changes that keep it readable in greyscale.",
  [("lecture#mm-w11-design", "Week 11: legibility claims must be supported by a measured contrast ratio."),
   ("lab#mm-w11-brief", "Lab 11 brief: measure the contrast of your slide palette and report the figures.")],
  ("lecture#mm-w11-2019", "Archived note: judge readability on your own screen."),
  ["ratio", "threshold", "measure", "colour alone"]),

# ---------------------------------------------------------------- Software Engineering
C("se_requirements", "Software Engineering", "requirements versus solutions",
  [("Says a requirement states a need, not an implementation", "a requirement says what the user must achieve, not which widget to use"),
   ("Says requirements should be testable", "you must be able to say whether the finished system meets it"),
   ("Says the stated request may hide the real need", "the first request is often a proposed solution to an unstated problem"),
   ("Says constraints and quality attributes belong in the requirements", "response time, offline use and accessibility are requirements too")],
  "treating the client's proposed solution as the requirement, which hides the need and forecloses better designs",
  "The client said they want a dropdown of all 4,000 students, so the requirement is a dropdown with 4,000 entries.",
  ("Replace the dropdown with a search field, because dropdowns are bad for long lists.",
   "the design is better but it is asserted from a usability rule rather than from the need the client was trying to meet"),
  "Requirements describe what the system should do.",
  "Use user stories with acceptance criteria.",
  "Write the need and its test - the user must find a student in a few seconds - and let the control be a design decision measured against it.",
  "A requirement expressed as a widget cannot be tested for success or satisfied a better way, which is what makes it the wrong unit of specification.",
  "Rewrite three of your requirements as need plus acceptance test, then list two designs that would each satisfy them.",
  "Why does the client want the dropdown? What are they doing the moment before they open it?",
  "Ask what the user is trying to accomplish, then write the test for success.",
  "Requirements capture needs and the tests for them; solutions are how you meet them. A request for a dropdown is already a design, and accepting it hides the goal - finding one student quickly - and blocks the search field, the recent-list, or the scan-the-id-card option. Write each requirement so it is testable and solution-neutral, and record constraints and quality attributes explicitly, because those are what usually decide between candidate designs.",
  "A lecturer asks for an Excel export. Write the underlying requirement and two designs that satisfy it.",
  [("lecture#se-w3-requirements", "Week 3: requirements must be testable and solution-neutral; the assignment marks acceptance criteria."),
   ("lab#se-w3-brief", "Lab 3 brief: interview the supplied client transcript and separate needs from proposed solutions.")],
  ("lecture#se-w3-2018", "Archived note: record the client's request verbatim as the requirement."),
  ["need", "testable", "solution", "criteria"]),

C("se_code_review", "Software Engineering", "code review",
  [("Says review checks correctness and comprehensibility", "a reviewer checks that the change is right and that someone else can maintain it"),
   ("Says small changes are reviewable and large ones are not", "a small focused change gets real scrutiny, a huge one gets a rubber stamp"),
   ("Says review comments address the code, not the person", "feedback is about the change, not the author"),
   ("Says review spreads knowledge across the team", "the second reader learns the part of the system they did not write")],
  "that review is a quality gate performed by a senior person on finished work, rather than a shared reading that improves the change and the team",
  "Review is for beginners' code, so experienced developers can merge their own work to save time.",
  ("Keep pull requests small, because large ones take longer to review.",
   "the practice is right but the reason is review quality: beyond a certain size, reviewers stop finding defects rather than taking longer"),
  "Code should be reviewed before merging.",
  "Write unit tests for new features.",
  "Submit small changes with a stated intent, and treat review as two people reading rather than a gate one person operates.",
  "Reviewer attention falls off sharply with change size, so a 2,000-line pull request produces approval without scrutiny, which is worse than no review because it signals confidence.",
  "Split your current branch into three reviewable changes, submit the first with a one-paragraph intent, and note the comments you get.",
  "Your last pull request touched 40 files. What would a reviewer realistically check in twenty minutes?",
  "Ask what the reviewer can actually hold in their head at once.",
  "Review has three payoffs: defects found, comprehensibility tested on a real second reader, and knowledge spread so the system does not have single points of failure. All three depend on size - past a few hundred lines, reviewers approve rather than read. So the skill being assessed is packaging: small changes, a stated intent, tests included, and comments written about the code. Self-merging removes the second reader, which is the whole mechanism.",
  "You must ship a refactor touching 30 files. Describe how you would package it for genuine review.",
  [("lecture#se-w8-review", "Week 8: review practice is assessed on change size, stated intent and comment quality."),
   ("lab#se-w8-brief", "Lab 8 brief: review a classmate's pull request and record the defects you found.")],
  ("lecture#se-w8-2017", "Archived note: code review is only necessary for junior developers."),
  ["size", "intent", "reader", "knowledge"]),

# ---------------------------------------------------------------- Professional Computing
C("prof_licensing", "Professional Computing", "software licensing and reuse",
  [("Says code found online is copyrighted by default", "published code is not automatically free to reuse"),
   ("Says the licence sets the conditions", "the licence states what you may do and what you must do in return"),
   ("Distinguishes permissive and copyleft terms", "some licences require derived work to carry the same licence"),
   ("Says attribution requirements must be honoured", "most licences require the notice to be kept")],
  "that public availability means public domain, so anything visible online can be pasted into your project",
  "The snippet was posted publicly online, so it is free to use and I do not need to credit anyone.",
  ("Use a permissively licensed library rather than copying the snippet, because libraries are better engineered.",
   "the decision is sound but the reason is the licence terms, not code quality"),
  "You should credit your sources.",
  "Use version control for your project.",
  "Check the licence before reusing, keep the notice it requires, and record the source in your project documentation.",
  "Copyright attaches on creation, so the default for published code is all rights reserved unless a licence says otherwise.",
  "List every third-party file in your project with its source and licence, and add the notices any of them require.",
  "Who owns the snippet you pasted, and what did they say you may do with it?",
  "Find the licence file before the code. If there is none, that is itself the answer.",
  "Publication is not permission. Code is copyrighted on creation, and a licence is the owner's grant of specific rights - permissive ones typically want attribution and a notice, copyleft ones require derived work to carry the same terms, and an unlicensed snippet grants nothing. For coursework this matters twice over: the licence is a legal condition, and the reuse is also an academic honesty question your brief will have rules about.",
  "Your project uses a copyleft component and the client wants to keep the source closed. Explain the conflict and two ways out.",
  [("lecture#prof-w8-licensing", "Week 8: third-party code must be listed with its licence; unlicensed reuse loses marks."),
   ("template#prof-w8-inventory", "Course template: a dependency inventory table with source, licence and notice requirements.")],
  ("lecture#prof-w8-2018", "Archived note: publicly posted code may be reused freely."),
  ["licence", "attribution", "copyleft", "default"]),

C("prof_bias", "Professional Computing", "bias in automated decisions",
  [("Says a model reflects the data it was trained on", "patterns in historical data are reproduced by the model"),
   ("Says removing the sensitive attribute is insufficient", "other fields can stand in for the removed attribute"),
   ("Says harm depends on how the output is used", "a screening tool that filters applicants causes different harm from one that ranks them"),
   ("Names a check", "measure error rates separately for affected groups")],
  "that a system is fair because it does not read the sensitive field, when correlated fields carry the same information",
  "We removed gender from the training data, so the shortlisting model cannot be biased.",
  ("Measure the model's error rates per group, because you should always evaluate on subgroups.",
   "the measurement is the right move but the reason should be proxy variables reproducing the pattern you removed"),
  "Algorithms can be biased.",
  "Get ethical approval before collecting data.",
  "Measure outcomes and error rates per affected group, because proxies such as school, area or career gaps carry the attribute you deleted.",
  "Models fit whatever correlates with the label, so deleting one column leaves every correlated column doing the same work.",
  "Compute your model's false-positive and false-negative rates separately for each group in your data and report the gaps.",
  "Which other fields in your data would let someone guess the attribute you removed?",
  "Try to predict the removed attribute from the remaining columns. That result is your answer.",
  "A model learns the patterns in its training data, including the ones you would not endorse. Dropping the sensitive column rarely helps, because proxies - address, school, gaps in employment, name-derived features - carry the same signal. The professional response is measurement and disclosure: evaluate error rates per group, state the intended use and its limits, keep a human decision point where the stakes are high, and document what you could not test.",
  "Your marking-support tool scores essays. Name two groups it could disadvantage and the check you would run before deployment.",
  [("lecture#prof-w10-fairness", "Week 10: automated decision systems must be evaluated per affected group and the limits documented."),
   ("case#prof-w10-hiring", "Class case: a shortlisting tool trained on ten years of hiring decisions reproduced the historical pattern after the gender field was removed.")],
  ("lecture#prof-w10-2017", "Archived note: removing sensitive attributes makes a model fair."),
  ["proxy", "subgroup", "error rate", "use"]),

# ---------------------------------------------------------------- Research Methods
C("rm_literature_review", "Research Methods", "literature reviews",
  [("Says a review synthesises rather than summarises", "a review organises sources around claims, not one paragraph per paper"),
   ("Says it must identify agreement and disagreement", "the review shows where the literature converges and where it conflicts"),
   ("Says it establishes the gap your work addresses", "the review ends by naming what is missing"),
   ("Says sources must be evaluated, not just cited", "you assess the quality and relevance of each source")],
  "that a literature review is a stack of summaries arranged by author, rather than an argument organised by question",
  "I wrote one paragraph per paper in the order I read them, so my literature review is complete.",
  ("Group the sources by theme rather than by paper, because it reads better.",
   "the structure is right but its purpose is to expose agreement, conflict and the gap, not readability"),
  "A literature review surveys existing work.",
  "Cite in the required referencing style.",
  "Reorganise around claims: for each one, who supports it, who disputes it, and what nobody has settled - and end on the gap your study addresses.",
  "Arranging by source hides the disagreements, which are exactly the material a reader needs to see that your question is open.",
  "Take your five sources, write the three claims they address, and place each source under the claims it supports or disputes.",
  "Two of your papers disagree. In your current draft, where would a reader notice that?",
  "Reorganise the same sources by claim instead of by author and see what appears.",
  "A review is an argument, not an annotated bibliography. Organise by claim: for each, state what is agreed, where findings conflict and why - method, sample, context - and what remains untested. That structure does three jobs: it shows you have read critically, it justifies your question by exposing a real gap, and it gives your method section something to answer to. One paragraph per paper cannot do any of them.",
  "Two studies report opposite effects. Write the two sentences your review needs about them.",
  [("lecture#rm-w2-review", "Week 2: reviews are marked on synthesis, on treatment of conflicting findings, and on the gap identified."),
   ("rubric#rm-w2-review", "Review rubric: source-by-source summaries score in the lowest band.")],
  ("lecture#rm-w2-2018", "Archived note: summarise each source in turn in the order read."),
  ["synthesis", "conflict", "gap", "claim"]),

C("rm_significance", "Research Methods", "statistical significance and importance",
  [("Says significance concerns compatibility with the null hypothesis", "a small p-value means the data would be unlikely if the null were true"),
   ("Says it is not a measure of effect size", "significance does not say how large the difference is"),
   ("Says large samples make tiny effects significant", "with enough data, a trivial difference reaches significance"),
   ("Says effect size and interval should be reported", "report the size of the difference with a confidence interval")],
  "reading a significant result as an important one, because the word means important in ordinary use",
  "The difference was statistically significant, so the new method is substantially better than the old one.",
  ("Report the confidence interval as well as the p-value, because journals expect it.",
   "the practice is right but the reason is that the interval shows the size and precision of the effect, which the p-value does not"),
  "A p-value below 0.05 is significant.",
  "Randomise participants between conditions.",
  "Report the effect size with its interval and interpret it against what matters in context, rather than resting on the threshold.",
  "The p-value combines effect size and sample size, so it can be small because the effect is large or merely because the sample is, and only the effect size separates those.",
  "Recompute your result with the effect size and its confidence interval, then state whether that size would change anyone's decision.",
  "Your sample was 40,000 and the difference was half a mark. What made the p-value small?",
  "Separate two questions: is there a difference, and is it big enough to matter.",
  "Significance answers a narrow question: would data like this be surprising if there were no effect? It is driven by both effect size and sample size, so with a big enough sample a difference too small to act on will clear the threshold - and with a small sample a real effect can miss it. Report the estimated effect with a confidence interval, interpret it in units your reader cares about, and treat the threshold as a convention rather than a verdict.",
  "Your study finds a two-percent improvement, p below 0.01, in a sample of 20,000. Write the sentence you would put in the discussion.",
  [("lecture#rm-w8-inference", "Week 8: results sections must report effect sizes with intervals, not p-values alone."),
   ("rubric#rm-w8-results", "Results rubric: a claim of practical importance requires an effect size and its interval.")],
  ("lecture#rm-w8-2019", "Archived note: a significant result establishes practical importance."),
  ["effect size", "interval", "sample", "threshold"]),

# ---------------------------------------------------------------- Computer Organization
C("co_amdahl", "Computer Organization", "parallel speedup and its limits",
  [("Says only the parallel portion speeds up", "the part that must run serially does not get faster with more cores"),
   ("States the ceiling implied by the serial fraction", "if a tenth is serial, the best possible speedup is about ten times"),
   ("Says coordination adds overhead", "synchronisation and communication eat into the theoretical gain"),
   ("Says you should measure the serial fraction first", "profile to find what fraction is actually parallelisable")],
  "that adding cores multiplies performance, because the work is imagined as uniformly divisible",
  "We moved from 4 cores to 16, so the job should finish four times faster.",
  ("Profile before parallelising, because optimisation should be measurement-driven.",
   "the discipline is right but the specific reason here is that the serial fraction caps the achievable speedup"),
  "More cores means faster execution.",
  "Use a thread pool to manage workers.",
  "Measure the serial fraction and compute the ceiling before buying cores, then attack the serial part instead.",
  "Total time is the serial part plus the parallel part divided by the core count, so as cores grow the serial part dominates and sets a hard ceiling.",
  "Profile your job into serial and parallel time, compute the theoretical ceiling, and compare it with your measured speedup at 4 and 16 cores.",
  "A fifth of your job cannot be parallelised. What is the best possible speedup with infinite cores?",
  "Split the measured runtime into the part that can be divided and the part that cannot, then do the arithmetic.",
  "Speedup is bounded by what cannot be divided. With a serial fraction s, the ceiling is 1/s no matter how many cores you add - a tenth serial caps you at ten times, and coordination overhead pulls the real figure lower. So the productive order is: profile, find the serial fraction, attack it (better algorithm, removed contention, batched I/O), and only then add cores. Reporting the measured speedup against the computed ceiling is what makes a performance claim credible.",
  "Your measured speedup at 16 cores is 3.2 against a ceiling of 8. Name two plausible causes and how you would distinguish them.",
  [("lecture#co-w10-parallel", "Week 10: speedup claims must be compared against the ceiling implied by the measured serial fraction."),
   ("lab#co-w10-brief", "Lab 10 brief: profile the supplied job, compute its ceiling, and measure speedup at two core counts.")],
  ("lecture#co-w10-2018", "Archived note: doubling cores halves running time."),
  ["serial fraction", "ceiling", "overhead", "profile"]),

C("co_number_repr", "Computer Organization", "number representation and overflow",
  [("Says fixed-width integers have a finite range", "a fixed-width integer can only represent a bounded range of values"),
   ("Says exceeding the range wraps or errors", "going past the maximum wraps around or raises an error depending on the language"),
   ("Says signed and unsigned differ in range and behaviour", "the same bits mean different values depending on signedness"),
   ("Says the type must be chosen from the expected range", "pick a width that covers the values your data can reach")],
  "that a variable holds whatever number you assign to it, because the abstraction usually hides the width",
  "The counter went negative after a large upload, so there must be a subtraction bug somewhere in the code.",
  ("Use a 64-bit type for the byte counter, because bigger types are safer.",
   "the change works but the reason should be the computed maximum for that field, not a preference for larger types"),
  "Integers have a maximum value.",
  "Floating point cannot represent all decimals exactly.",
  "Size the type from the largest value the field can reach, and treat the wrap as arithmetic hitting the width rather than as a logic bug.",
  "Fixed-width arithmetic discards the carry beyond the top bit, so a signed counter crossing its maximum reappears at the most negative value.",
  "Print your counter's type and maximum, compute the largest value your data can reach, and say whether the margin is safe.",
  "Your counter is 32-bit signed. What is the largest value it can hold, and what did your upload total reach?",
  "Compare the value you reached with the maximum the type can hold, before looking for a logic error.",
  "A fixed-width integer is a finite set of bit patterns. Exceed the top and the carry is discarded: in two's complement, a signed value crossing its maximum reappears as the most negative one - which looks exactly like a mysterious subtraction. Some languages raise instead, and unsigned types wrap to zero. The design step is to compute the maximum your field can reach, including growth, and select the width from that rather than from habit.",
  "A field stores milliseconds since an epoch in 32 bits. Say when it fails and what you would change.",
  [("lecture#co-w4-representation", "Week 4: type selection must be justified by the range the data can reach; overflow behaviour is examinable."),
   ("lab#co-w4-brief", "Lab 4 brief: demonstrate an overflow in a fixed-width counter and correct the type choice.")],
  ("lecture#co-w4-2017", "Archived note: integer variables grow as needed."),
  ["width", "wrap", "range", "signed"]),

# ---------------------------------------------------------------- more SE / Professional
C("se_technical_debt", "Software Engineering", "technical debt",
  [("Says debt is a deliberate or accidental shortcut with ongoing cost", "a shortcut in the code keeps costing time until it is repaid"),
   ("Says the cost is paid in future change, not in running the code", "the program still works; what suffers is the next change to it"),
   ("Says debt should be recorded and prioritised", "write it down with its cost so it can be scheduled rather than forgotten"),
   ("Says some debt is a reasonable trade", "taking a shortcut to meet a deadline can be the right call if it is repaid")],
  "treating messy code as a matter of taste, so cleanup is optional polish rather than an investment with a measurable return",
  "The code works and passes the tests, so refactoring it would just be making it prettier.",
  ("Refactor the payment module before adding the new provider, because clean code is easier to work with.",
   "the sequencing is right, but the argument should be concrete: the duplication means the new provider must be added in four places"),
  "Technical debt slows teams down.",
  "Write documentation for your code.",
  "Record the shortcut with the cost it imposes on the next change, then repay the items that sit in the path of planned work.",
  "Debt is paid in modification cost, so it is invisible while nothing changes and expensive the moment a feature touches that code.",
  "List three shortcuts in your project, estimate the extra hours each adds to the next feature touching it, and repay the most expensive one.",
  "The next feature touches this module. How many places will you have to change, and how many would it be if the duplication were gone?",
  "Price the debt against a specific upcoming change rather than against an idea of tidiness.",
  "Technical debt is not untidiness; it is borrowed time with interest paid in every future modification. Working code with duplicated payment logic is fine until the fifth provider arrives and each change must be made in four places with four chances to get it wrong. That makes debt a scheduling question: record each item with the cost it imposes and the work it blocks, repay what sits in the path of the roadmap, and accept the rest knowingly rather than by drift.",
  "Your deadline is Friday and the clean fix takes two days. Write the decision and the repayment plan you would record.",
  [("lecture#se-w11-debt", "Week 11: debt items must be recorded with an estimated cost and the work they block."),
   ("template#se-w11-register", "Course template: a debt register with item, cost per change, and blocked work.")],
  ("lecture#se-w11-2018", "Archived note: refactoring is cosmetic and optional."),
  ["cost", "change", "record", "trade"]),

C("prof_escalation", "Professional Computing", "raising a concern at work",
  [("Says a concern should be raised with evidence, not impressions", "state what you observed and what it implies, with the evidence"),
   ("Says you start with the person or team responsible", "raise it first with the people who can fix it"),
   ("Says you escalate if it is not addressed and the risk is real", "if nothing happens and the risk stands, take it to the next level"),
   ("Says you keep a factual record", "note dates, what you reported and the response")],
  "that speaking up is a matter of confidence, so the choice is between staying quiet and making an accusation",
  "I think the logging is leaking personal data but I am an intern, so it is not my place to say anything.",
  ("Email the team lead with the log excerpt and the affected field, because it is better to put it in writing.",
   "the action is right but the reason should be that a written, evidenced report can be acted on and tracked, not just that writing is safer"),
  "You should report ethical concerns.",
  "Follow the company's coding standards.",
  "Write what you observed, what it risks and what you recommend, send it to the team that owns the code, and keep the record.",
  "An evidenced, specific report is actionable and reviewable, which is what turns a concern into a decision someone is accountable for.",
  "Draft a five-line report of your observation - what you saw, where, what it risks, what you suggest, what you need - and identify who owns that code.",
  "What exactly did you observe, and which field was in the log line?",
  "Separate the observation from the accusation. Report the first; you are not required to prove the second.",
  "Raising a concern is a professional skill with a shape. State the observation and the evidence, say what it risks and to whom, propose a next step, and send it to the people who own the system. Escalate only if it is not addressed and the risk persists, and keep a factual dated record throughout - it protects the organisation and you. Seniority is not the qualification; being the person who noticed is. If a specific institutional channel applies, check what your own organisation's policy actually says rather than assuming one exists.",
  "You reported a logging issue two weeks ago and nothing changed. Write your next step and its justification.",
  [("lecture#prof-w12-responsibility", "Week 12: professional responsibility answers must show evidence, the correct first recipient, and escalation only after non-response."),
   ("case#prof-w12-logging", "Class case: an intern finds identifiers written to an application log and reports it to the owning team with the log excerpt.")],
  ("lecture#prof-w12-2017", "Archived note: junior staff should not raise concerns directly."),
  ["evidence", "owner", "escalate", "record"]),

]
