# -*- coding: utf-8 -*-
"""Second concept bank (Task C of the corrective pass).

Same schema as content/concepts.py - see that file for the field contract.
These 43 concepts take the bank from 47 to 90, spread across the same 15
controlled course titles, so the drill task types stop recycling a small set of
ideas and the evaluation splits can hold 12+ concept families per task type.
"""

from content.concepts import C

CONCEPTS_B = [

# ---------------------------------------------------------------- Programming
C("prog_string_immutable", "Introduction to Programming", "string immutability",
  [("Says strings cannot be modified in place", "a string cannot be changed after it is created"),
   ("Says an apparent edit creates a new object", "the replace call returns a new string rather than editing the old one"),
   ("Says the result must be assigned or it is lost", "you have to assign the result back or nothing changes"),
   ("Notes the cost of repeated concatenation in a loop", "building a string by adding in a loop copies the whole thing each time, so join is better")],
  "that a method called on a string edits that string, because the call reads like an instruction to change it",
  "I called text.replace on the string inside the loop, so the text is cleaned now. The variable should hold the cleaned version.",
  ("Use join instead of adding strings in a loop, because join is the built-in way to do it.",
   "the advice is right but the reason is convention, not the repeated copying that makes concatenation quadratic"),
  "Strings are immutable in Python.",
  "Use f-strings for formatting.",
  "Assign the result: the call returns a new string and leaves the original untouched.",
  "Immutability means every apparent edit allocates a new object, so a call whose result you discard has no visible effect at all.",
  "Print the string before and after your replace call without assigning, then with assignment, and explain the two outputs.",
  "You called replace and printed the variable afterwards. What did the call hand back, and where did it go?",
  "Follow the return value. If nothing catches it, ask what the function could possibly have changed.",
  "Strings are immutable: replace, strip, upper and the rest all return a new string and leave the original alone. A call with no assignment is a no-op. The same property explains the performance trap - adding in a loop copies the accumulated text every iteration, which is why you collect the pieces in a list and join once at the end.",
  "A function receives a string and a list, and modifies both. Say which change the caller sees and why they differ.",
  [("lecture#prog-w6-strings", "Week 6: string methods return new values; the lab checks that results are assigned."),
   ("lab#prog-w6-brief", "Lab 6 brief: clean a list of names and report the time taken by concatenation versus join.")],
  ("lecture#prog-w6-2018", "Archived note: string methods modify the string in place."),
  ["immutable", "returns", "assign", "join"]),

C("prog_input_types", "Introduction to Programming", "input and type conversion",
  [("Says console input arrives as text", "input returns a string even when the user typed digits"),
   ("Says comparison or arithmetic on that text misbehaves", "comparing a string to a number is false or an error, and adding concatenates"),
   ("Says conversion must be explicit", "wrap it in int or float before using it as a number"),
   ("Says conversion can fail and must be handled", "a non-numeric entry raises an error, so validate or catch it")],
  "that the program can tell a number from text by looking at it, when the type is fixed by where the value came from",
  "The user typed 25 so the variable holds a number. The comparison with 18 should work fine.",
  ("Wrap the input in int, because you always convert input in Python.",
   "the conversion is right but the reason is a memorised ritual rather than the fact that input returns text"),
  "You need to convert the input.",
  "Use a while loop to keep asking until the user is done.",
  "Convert explicitly with int or float, and handle the failure case where the text is not a number at all.",
  "The type of a value comes from what produced it, not from what it looks like, so digits read from a console are still characters until you convert them.",
  "Print the type of the input value, then compare it with a number before and after conversion, and record all three results.",
  "Your comparison with 18 came out false for an input of 25. What is the type of each side of that comparison?",
  "Ask what input hands back, before you ask what the user typed.",
  "Console input is text. Digits typed by a user are characters, so comparison against a number is either false or a type error, and the plus operator concatenates instead of adding. Convert explicitly with int or float at the boundary where the value enters your program, and treat conversion as fallible: wrap it so a typed word gives a re-prompt rather than a crash. Converting once at the edge also keeps the rest of the code free of defensive checks.",
  "Your program reads an age and a price from the same form. Say which conversion each needs and what you do when either fails.",
  [("lecture#prog-w2-io", "Week 2: input returns a string; conversions must be explicit and guarded."),
   ("lab#prog-w2-brief", "Lab 2 brief: read two numbers from the console, add them, and handle a non-numeric entry.")],
  ("lecture#prog-w2-2017", "Archived note: input detects numbers automatically."),
  ["string", "convert", "int", "validate"]),

C("prog_shallow_copy", "Introduction to Programming", "copying nested structures",
  [("Says assignment binds another name to the same object", "assigning a list to a new variable does not copy it"),
   ("Says a slice or list call copies one level", "a slice gives a new outer list"),
   ("Says inner objects are still shared after a shallow copy", "the inner lists are the same objects in both copies"),
   ("Names the deep copy when independence is required", "use a deep copy when the nested parts must be independent")],
  "that copying is a single operation with one meaning, when it has a depth and the default depth is one level",
  "I copied the grid with a slice, so changing the copy cannot affect the original. The shared rows must be a bug elsewhere.",
  ("Use copy.deepcopy for the grid, because deep copies are safer.",
   "it does fix this case, but the justification should be that the nested rows must be independent, since deep copying costs time and memory"),
  "Lists are mutable so you should copy them.",
  "Tuples cannot be changed.",
  "Copy to the depth your program needs: a slice duplicates the outer list only, so nested rows stay shared until you deep copy.",
  "A shallow copy duplicates the container and re-uses the references inside it, so mutating an inner object is visible through both containers.",
  "Build a two-row grid, slice-copy it, mutate one inner row, print both, then repeat with a deep copy and compare.",
  "Your slice made a new outer list. What is stored inside those two lists - values, or references to the same rows?",
  "Draw the boxes and arrows for the two variables. The answer is in how many arrows point at each inner row.",
  "Assignment binds a second name to one object; a slice or list() call makes a new outer container holding the same inner references - that is a shallow copy; copy.deepcopy rebuilds the whole tree. So for a grid of rows, a slice protects you against replacing a row but not against mutating one. Pick the depth deliberately, because deep copies are not free and are wrong when sharing is intended.",
  "A dictionary of student records is copied and one record's marks list is appended to. Predict what the original shows and justify it.",
  [("lecture#prog-w10-objects", "Week 10: names bind to objects; copies have a depth, and the lab marks the distinction."),
   ("lab#prog-w10-brief", "Lab 10 brief: demonstrate a shallow copy surprise in a nested structure, then fix it.")],
  ("lecture#prog-w10-2019", "Archived note: slicing a list produces a fully independent copy."),
  ["shallow", "deep", "reference", "nested"]),

C("prog_boolean_logic", "Introduction to Programming", "conditions and short-circuit evaluation",
  [("Says and requires both sides, or requires either", "and is true only when both are true, or is true when at least one is"),
   ("Says each side must be a complete comparison", "you cannot write x equals 1 or 2, each side needs its own comparison"),
   ("Says evaluation short-circuits left to right", "if the left side settles it, the right side is never evaluated"),
   ("Uses short-circuiting as a guard", "check the list is non-empty before indexing it in the same condition")],
  "that a condition is read the way a spoken sentence is read, so the comparison carries across the connector",
  "I wrote if grade == 'A' or 'B' and it matched everything. Python must be treating any letter as a match.",
  ("Put the check for an empty list first in the condition, because it reads more clearly that way.",
   "the ordering is correct but it is load-bearing, not cosmetic - it is what stops the index error"),
  "Use and or or to combine conditions.",
  "Indentation defines blocks in Python.",
  "Write a full comparison on each side, or test membership in a collection, and rely on left-to-right short-circuiting when the first test guards the second.",
  "The or operator takes two values, not one comparison and one value, so a bare letter is evaluated as a truthy value and always wins.",
  "Evaluate your condition on paper for three inputs, then rewrite it with a membership test and re-run all three.",
  "Break your condition at the or. What exactly is on the right-hand side, and is it true or false on its own?",
  "Evaluate each side separately, as the interpreter does. One of the two is not a comparison at all.",
  "Each side of and/or must be its own truth value. Writing grade == 'A' or 'B' evaluates grade == 'A', then 'B', which is a non-empty string and therefore always true - so the whole condition is always true. Use grade in ('A', 'B'). The second property worth knowing is short-circuiting: with and, the right side runs only if the left is true, which is exactly what lets you write a guard and an access in one condition safely.",
  "Write one condition that safely reports whether the first item of a possibly empty list is negative, and say why the order matters.",
  [("lecture#prog-w5-conditions", "Week 5: each operand of a boolean operator must be a complete test; short-circuiting is examinable."),
   ("lab#prog-w5-brief", "Lab 5 brief: fix three conditions that pass tests for the wrong reason.")],
  ("lecture#prog-w5-2018", "Archived note: comparisons carry across or in the usual spoken sense."),
  ["membership", "short-circuit", "operand", "guard"]),

# ---------------------------------------------------------------- Data Structures
C("ds_circular_buffer", "Data Structures", "queues on top of arrays",
  [("Says removing from the front of an array shifts everything", "dequeuing from index zero moves every remaining element down"),
   ("Says that makes a naive array queue O(n) per removal", "each dequeue costs a full shift, so the queue is linear per operation"),
   ("Describes head and tail indices wrapping around", "keep a head and tail index and wrap them with the modulus"),
   ("Says the buffer needs a full or empty distinction", "you track a count or leave one slot empty to tell full from empty")],
  "that the data structure's cost is decided by its interface rather than by the layout underneath it",
  "A queue is O(1) for enqueue and dequeue, so implementing it on an array is fine as it is.",
  ("Use a circular buffer for the audio pipeline, because it is the standard structure there.",
   "the choice fits, but the reason is precedent rather than the constant-time wrap that avoids shifting"),
  "A queue removes from the front.",
  "Linked lists avoid resizing costs.",
  "Keep head and tail indices and wrap with the modulus, so no element ever moves and both operations stay constant time.",
  "Shifting is what costs: moving the head index instead of the data turns a linear dequeue into an arithmetic update.",
  "Implement both versions, time 100,000 enqueue and dequeue pairs on each, and explain the ratio you measure.",
  "Your queue holds 10,000 items and you remove the front one. How many elements change position?",
  "Count the memory writes per dequeue in your implementation, not the operations in the interface.",
  "The ADT promises constant-time enqueue and dequeue; the implementation has to deliver it. Removing from index zero of an array shifts every remaining element, so the naive version is O(n). A circular buffer keeps head and tail indices and advances them modulo the capacity, so data never moves; you distinguish full from empty with a count or a reserved slot, and grow by copying once when the capacity is exhausted.",
  "Your circular buffer is full and a producer wants to write. Give two policies for that case and say what each one loses.",
  [("lecture#ds-w4-queues", "Week 4: queue implementations are marked on the cost per operation, not on the interface."),
   ("lab#ds-w4-brief", "Lab 4 brief: implement an array queue two ways and report timings for 100,000 operations.")],
  ("lecture#ds-w4-2018", "Archived note: any queue implementation gives constant-time operations."),
  ["shift", "wrap", "index", "constant"]),

C("ds_heap_priority", "Data Structures", "heaps and priority queues",
  [("Says a heap keeps the extreme element at the root", "the smallest or largest element is always at the top"),
   ("Says a heap is partially ordered, not sorted", "only the parent-child relation holds, siblings are unordered"),
   ("Gives the costs of insert and extract", "insert and extract are both O(log n) because the element sifts through the height"),
   ("Says peeking at the extreme is constant time", "reading the top element without removing it is O(1)")],
  "that a priority queue must keep everything sorted, so maintaining it costs as much as sorting",
  "A priority queue keeps the list sorted at all times, so every insert costs O(n log n) to re-sort.",
  ("Use a heap for the scheduler, because heaps are fast.",
   "the structure is right but 'fast' skips the property that matters - you only ever need the next item, not a full order"),
  "A priority queue returns the highest priority item first.",
  "Sorting algorithms include merge sort and quicksort.",
  "Use a heap: it maintains only the parent-child ordering you need, so inserts and extractions are logarithmic rather than full re-sorts.",
  "Keeping a total order is more work than any single query needs; the heap invariant is the weakest ordering that still guarantees the top element.",
  "Insert 1,000 random values into a sorted list and into a heap, timing both, then extract the minimum 1,000 times and compare again.",
  "Your scheduler only ever asks for the next job. How much of the ordering do you actually need to maintain?",
  "Write down the single query your structure must answer, then ask what the weakest invariant supporting it is.",
  "A binary heap maintains one rule: every parent outranks its children. That is strictly weaker than sorted order, which is why insert and extract cost O(log n) - the element sifts up or down the height - while reading the top is O(1). Printing a heap looks unsorted, and that is correct, not a bug. Choose it when you repeatedly need the next extreme element; choose a sorted structure when you need ranges or full order.",
  "You need the ten largest of a million streamed values with bounded memory. Design it with a heap and say which extreme the heap should hold.",
  [("lecture#ds-w9-heaps", "Week 9: heaps are partially ordered; answers must state the invariant and the cost per operation."),
   ("lab#ds-w9-brief", "Lab 9 brief: implement a binary heap and compare it with a sorted list under the same workload.")],
  ("lecture#ds-w9-2017", "Archived note: a priority queue is a sorted list."),
  ["invariant", "partial", "log", "root"]),

C("ds_graph_representation", "Data Structures", "graph representations",
  [("Describes an adjacency matrix and its space cost", "a matrix stores a cell for every pair, so it uses n squared space"),
   ("Describes an adjacency list and its space cost", "a list stores only the edges that exist, so it uses space proportional to the edges"),
   ("Says edge lookup is constant in a matrix", "checking whether two nodes are connected is O(1) in a matrix"),
   ("Says neighbour iteration favours the list", "listing a node's neighbours is proportional to its degree in an adjacency list")],
  "that one representation is simply better, rather than each being better for a different question and a different density",
  "Adjacency lists are the efficient representation, so I will use a list for the 500-node dense network regardless of the queries.",
  ("Use an adjacency matrix for the road network, because matrices are easier to index.",
   "convenience is not the criterion here - the network is sparse, so the matrix wastes almost all of its cells"),
  "Graphs can be stored as a matrix or a list.",
  "Breadth-first search uses a queue.",
  "Choose by density and by the query you run most: matrices for dense graphs and constant-time edge tests, lists for sparse graphs and neighbour walks.",
  "The matrix reserves a cell per pair whether or not an edge exists, so its cost tracks n squared while the list's tracks the number of edges.",
  "Compute both space costs for your actual graph, then time an edge-existence check and a full neighbour walk on each representation.",
  "Your graph has 500 nodes and 1,200 edges. How many cells does the matrix hold, and how many of them are non-zero?",
  "Work out the density first - edges over possible edges. That number chooses the representation.",
  "Two questions decide it: how dense is the graph, and what do you ask it? A matrix costs n squared space but answers 'is there an edge?' in constant time. A list costs O(n + e) and iterates a node's neighbours in degree time, which is what traversals actually do. Sparse graphs - road networks, social graphs - are overwhelmingly list territory; dense graphs with frequent pairwise tests are matrix territory.",
  "You must run both a traversal and many random edge tests on a mid-density graph. Propose a hybrid and say what it costs.",
  [("lecture#ds-w10-graphs", "Week 10: representation choices must be justified by density and by the dominant query."),
   ("lab#ds-w10-brief", "Lab 10 brief: store the supplied campus graph both ways and report memory and query timings.")],
  ("lecture#ds-w10-2018", "Archived note: adjacency lists are always the better representation."),
  ["density", "matrix", "neighbour", "space"]),

C("ds_set_membership", "Data Structures", "membership tests and the right container",
  [("Says list membership scans the list", "checking whether an item is in a list looks at each element in turn"),
   ("Says set and dictionary membership hash the key", "a set finds the item by hashing, so the test does not scan"),
   ("Gives the cost difference", "the list test is O(n) while the set test is about O(1)"),
   ("Notes what the set gives up", "a set has no order and cannot hold duplicates or unhashable items")],
  "that container choice is about what you store rather than about what you ask, so a list is the default for everything",
  "A list holds the seen ids fine. Checking membership inside the loop cannot be what makes the program slow.",
  ("Use a set for the seen ids, because sets remove duplicates automatically.",
   "the container is right, but the duplicate behaviour is a side effect - the reason is the constant-time membership test inside the loop"),
  "Sets are faster than lists.",
  "Dictionaries store key-value pairs.",
  "Put the collection you test against in a set, so the inner test stops scanning and the loop drops from quadratic to linear.",
  "A membership test inside a loop multiplies: an O(n) test inside an O(n) loop is O(n squared), which is why the same code is instant at 100 items and hangs at 100,000.",
  "Run your de-duplication over 100,000 ids with a list and with a set, time both, and plot the two curves against input size.",
  "Your loop runs 50,000 times and each pass checks a list of 50,000 ids. How many comparisons is that?",
  "Multiply the cost of the test by the number of times the loop performs it.",
  "The question is not what you store, it is what you ask. A list answers 'is this here?' by scanning; a set or dictionary answers it by hashing, in roughly constant time. Nest that test in a loop and the difference becomes quadratic against linear - the reason a script that was fine on sample data hangs on the real file. The trade is that sets are unordered, reject duplicates and require hashable elements.",
  "You need de-duplication and the original order preserved. Give the structure combination that does both and its cost.",
  [("lecture#ds-w5-containers", "Week 5: container choice is assessed on the dominant operation, with its cost stated."),
   ("lab#ds-w5-brief", "Lab 5 brief: de-duplicate a large id file and report timings for two container choices.")],
  ("lecture#ds-w5-2019", "Archived note: container choice rarely affects performance."),
  ["membership", "hash", "quadratic", "scan"]),

# ---------------------------------------------------------------- Algorithms
C("alg_sort_stability", "Algorithms", "sorting stability",
  [("Defines stability as preserving the order of equal keys", "a stable sort keeps equal elements in their original relative order"),
   ("Says stability matters when sorting in stages", "sorting by one field then another relies on the first order surviving"),
   ("Names a stable and an unstable algorithm", "merge sort is stable, quicksort as usually implemented is not"),
   ("Says a composite key is the alternative", "you can sort once on a tuple of both fields instead")],
  "that two sorted outputs with the same keys are interchangeable, because sorting is only about the key you named",
  "Both sorts produced the same order by grade, so the algorithms are equivalent and it does not matter which one I use.",
  ("Sort by name first, then by grade, because that is the order the report needs.",
   "the sequence is right but it only works because the second sort is stable, which the answer does not say"),
  "A stable sort keeps equal elements in order.",
  "Merge sort is O(n log n) in all cases.",
  "Either use a stable sort for the second pass, or sort once on a composite key, so the tie-breaking order is guaranteed rather than incidental.",
  "Stability is what makes a multi-pass sort compose: the earlier ordering survives inside each group of equal keys in the later pass.",
  "Sort your student list by name then by grade using a stable and an unstable sort, and show a group where the two disagree.",
  "Two students share a grade. What decides which of them is printed first?",
  "Look at only the rows with equal keys. The difference between the two outputs lives there.",
  "Stability is about ties: equal keys come out in the order they went in. It becomes load-bearing when you sort in stages - sort by name, then by grade, and a stable sort leaves each grade group in name order, while an unstable one scrambles it. Merge sort and most library sorts are stable; classic in-place quicksort is not. The alternative that does not depend on the implementation is a single sort on a composite key.",
  "Your report must be ordered by department, then by mark descending, then by name. Give the sort you would write and justify it.",
  [("lecture#alg-w7-sorting", "Week 7: multi-field ordering must state whether it relies on stability or a composite key."),
   ("lab#alg-w7-brief", "Lab 7 brief: produce a two-stage ordering and demonstrate what an unstable sort does to it.")],
  ("lecture#alg-w7-2018", "Archived note: all sorting algorithms produce identical output for the same key."),
  ["stable", "ties", "composite", "stage"]),

C("alg_memo_vs_tab", "Algorithms", "memoisation and tabulation",
  [("Says memoisation caches results of recursive calls", "you store each subproblem's answer the first time it is computed"),
   ("Says tabulation fills a table bottom-up", "you compute the small cases first and build up in a loop"),
   ("Says both remove the repeated work, not the subproblems", "each distinct subproblem is solved once in either approach"),
   ("Notes the practical differences", "recursion can overflow the stack, while tabulation may compute entries it never needs")],
  "that memoisation and tabulation are different algorithms rather than two schedules for computing the same recurrence",
  "Memoisation and tabulation give different answers for the same problem, so I need to pick the correct technique first.",
  ("Use tabulation for the large input, because loops are faster than recursion.",
   "tabulation is the right call here, but the reason is stack depth, not loop speed"),
  "Dynamic programming stores subproblem results.",
  "Recursion needs a base case.",
  "Write the recurrence once, then choose the schedule: top-down with a cache, or bottom-up with a table, driven by stack depth and by how many entries you need.",
  "Both approaches evaluate the same recurrence and the same set of distinct subproblems; they differ only in the order of evaluation and in what that order costs.",
  "Implement your recurrence both ways, assert the outputs match on 50 random inputs, and compare peak memory and running time.",
  "If both methods compute the same recurrence, what could make their answers differ?",
  "Write the recurrence on paper first. Then ask what changes when you evaluate it top-down versus bottom-up.",
  "They are the same dynamic program with different evaluation orders. Memoisation is the recurrence written recursively with a cache: it computes only the subproblems actually reached, and pays with stack frames. Tabulation is the same recurrence in a loop over an explicit table: no stack risk, easy to shrink to a rolling row, but it may fill entries nothing needs. Answers must agree; if they do not, the recurrence or the base case differs between your two versions.",
  "Your table for the knapsack is too large for memory. Say which schedule you would pick and how you would reduce the space.",
  [("lecture#alg-w10-dp", "Week 10: the recurrence is marked, not the schedule; both implementations must agree."),
   ("lab#alg-w10-brief", "Lab 10 brief: implement one recurrence twice and test that the two versions agree.")],
  ("lecture#alg-w10-2017", "Archived note: memoisation and tabulation solve different problem classes."),
  ["recurrence", "schedule", "cache", "table"]),

C("alg_bfs_dijkstra", "Algorithms", "shortest paths with and without weights",
  [("Says BFS gives fewest edges on unweighted graphs", "breadth-first search finds the path with the fewest hops"),
   ("Says BFS is wrong when edges have different weights", "with weights, the fewest hops may not be the cheapest route"),
   ("Names Dijkstra for non-negative weights", "Dijkstra expands the cheapest known node using a priority queue"),
   ("Says negative edges break Dijkstra", "with negative weights you need a different algorithm")],
  "that shortest means fewest steps, because that is what shortest means on a diagram with unlabelled edges",
  "Breadth-first search gives the shortest path, so it will find the cheapest route through the weighted road network.",
  ("Use Dijkstra for the delivery routes, because it is the standard shortest-path algorithm.",
   "the choice is right but the reason should be the weights: journey times differ per road, so hop count is not the cost"),
  "BFS explores level by level.",
  "Graphs can be directed or undirected.",
  "Match the algorithm to the cost model: BFS when every edge costs the same, Dijkstra when edge costs differ and are non-negative.",
  "BFS is optimal precisely because expanding by level orders nodes by cost when all edges cost one; unequal weights break that correspondence.",
  "Build a three-node example where the two-hop route is cheaper than the one-hop route, run BFS and Dijkstra on it, and compare the outputs.",
  "One road is two hops but quick; another is one hop but slow. Which does a hop-counting search return?",
  "Write the cost of each edge next to it. Then ask whether counting edges is the same as adding costs.",
  "BFS returns the path with the fewest edges, and that is the cheapest path only when every edge costs the same. Add weights and the correspondence breaks: the two-hop road can be faster than the one-hop one. Dijkstra restores optimality by always expanding the cheapest frontier node using a priority queue, valid while no weight is negative. Negative edges need Bellman-Ford, because Dijkstra's finality assumption no longer holds.",
  "A route planner must minimise time, but some links have a fixed toll. Say how you would encode that and which algorithm still applies.",
  [("lecture#alg-w12-paths", "Week 12: shortest-path answers must state the cost model before naming an algorithm."),
   ("lab#alg-w12-brief", "Lab 12 brief: run both searches over the supplied weighted campus graph and explain any disagreement.")],
  ("lecture#alg-w12-2018", "Archived note: breadth-first search returns the shortest path in any graph."),
  ["weights", "hops", "priority", "cost model"]),

C("alg_np_meaning", "Algorithms", "what NP-hard means for your project",
  [("Says NP-hard means no known polynomial algorithm for the exact optimum", "nobody knows a polynomial-time algorithm that always finds the exact optimum"),
   ("Says it does not mean the instance is unsolvable", "small or structured instances are often solved exactly in practice"),
   ("Names practical responses", "use heuristics, approximation algorithms or a solver and accept a good-enough answer"),
   ("Says you should state the quality guarantee", "report whether your answer is exact, within a bound, or simply the best found")],
  "reading a hardness class as a verdict on your instance, when it is a statement about worst cases across all instances",
  "Timetabling is NP-hard, so there is no point writing a solver. We will just do it by hand.",
  ("Use a heuristic for the timetable, because exact algorithms are too slow.",
   "the plan is right but 'too slow' is unexamined - for your instance size an exact solver may finish, and the answer should say how you checked"),
  "NP-hard problems are hard.",
  "Big-O measures growth.",
  "Size your instance first, then choose: exact solver if it finishes, otherwise a heuristic with a stated quality claim.",
  "Hardness is a worst-case statement over an infinite family; your project has one instance with a fixed size and structure, and that is an empirical question.",
  "Estimate your instance size, run an exact solver with a time limit, and report either the optimum or the best solution found with its bound.",
  "Your timetable has 40 courses and 12 rooms. What does NP-hardness predict about that specific instance?",
  "Separate the class from the instance. One is about all inputs; the other is the one on your desk.",
  "NP-hardness says no known algorithm solves every instance exactly in polynomial time, as the input grows without bound. It does not say your 40-course timetable is unsolvable - real instances are often small, structured or slack enough for an exact solver, and where they are not, heuristics and approximations give usable answers. What professional practice requires is honesty about which you produced: exact, within a proven factor, or best-found under a time limit.",
  "Your greedy timetable leaves two clashes. Describe how you would establish whether a clash-free timetable exists at all.",
  [("lecture#alg-w13-complexity", "Week 13: complexity classes describe worst cases; project write-ups must state the solution quality achieved."),
   ("lab#alg-w13-brief", "Lab 13 brief: run an exact solver with a time limit on the supplied instance and report the outcome.")],
  ("lecture#alg-w13-2019", "Archived note: NP-hard problems cannot be solved in practice."),
  ["worst case", "instance", "heuristic", "guarantee"]),

# ---------------------------------------------------------------- Databases
C("db_null_semantics", "Database Systems", "NULL in SQL",
  [("Says NULL means unknown, not zero or empty", "NULL is the absence of a value, not an empty string or a zero"),
   ("Says comparisons with NULL yield unknown", "equals NULL is never true, so you use IS NULL"),
   ("Says aggregates skip NULLs", "COUNT of a column ignores NULLs while COUNT star does not"),
   ("Says NULL affects joins and NOT IN", "NOT IN with a NULL in the list returns no rows")],
  "treating NULL as a value like any other, so it can be compared, counted and filtered in the ordinary way",
  "The query with 'WHERE phone = NULL' returns nothing, so every student must have a phone number recorded.",
  ("Use IS NULL rather than equals NULL, because that is the SQL syntax for it.",
   "the syntax is right but the reason is three-valued logic, which is what also breaks NOT IN and some joins"),
  "NULL means no value.",
  "Use COALESCE to provide defaults.",
  "Test with IS NULL, and check every aggregate, NOT IN and outer join in the query for the same three-valued logic trap.",
  "SQL comparisons return unknown rather than false when either side is NULL, and a WHERE clause keeps only rows that are true.",
  "Run three versions of your count - COUNT star, COUNT of the column, and a WHERE IS NULL - on the same table and reconcile the numbers.",
  "Your filter returned zero rows on a table you know has missing phone numbers. What did the comparison actually evaluate to?",
  "Evaluate the predicate for one row with a missing value. True, false, or something else?",
  "SQL uses three-valued logic: any comparison involving NULL evaluates to unknown, and WHERE keeps only rows where the predicate is true. Hence equals NULL never matches and you use IS NULL. The same rule explains the surprises: COUNT(column) skips NULLs while COUNT(*) does not, NOT IN over a list containing NULL returns nothing, and an outer join's padded rows behave the same way. Decide per column whether missing should be possible at all.",
  "A report shows an average that looks too high. Say how NULLs could produce that and how you would check.",
  [("lecture#db-w7-null", "Week 7: three-valued logic is examinable; predicates involving NULL must be justified."),
   ("lab#db-w7-brief", "Lab 7 brief: explain the row-count difference between three supplied queries over a table with missing values.")],
  ("lecture#db-w7-2018", "Archived note: NULL behaves like an empty string in comparisons."),
  ["unknown", "is null", "aggregate", "not in"]),

C("db_group_having", "Database Systems", "GROUP BY, WHERE and HAVING",
  [("Says WHERE filters rows before grouping", "WHERE is applied to individual rows before they are grouped"),
   ("Says HAVING filters groups after aggregation", "HAVING applies to the aggregated result, so it can use COUNT or SUM"),
   ("Says selected columns must be grouped or aggregated", "every non-aggregated column in the select list has to appear in GROUP BY"),
   ("Gives the logical order of evaluation", "the order is FROM, WHERE, GROUP BY, HAVING, SELECT, ORDER BY")],
  "that the clauses run in the order they are written, so any condition can go in any of them",
  "I put COUNT(*) > 5 in the WHERE clause and it failed, so the database must not support counting in filters.",
  ("Move the condition to HAVING, because HAVING is for aggregate conditions.",
   "correct as a rule, but the reason is the evaluation order - the count does not exist yet when WHERE runs"),
  "GROUP BY groups rows.",
  "Indexes speed up queries.",
  "Put row conditions in WHERE and group conditions in HAVING, following the logical evaluation order rather than the written order.",
  "Aggregates only exist after grouping, so a filter that runs before grouping cannot refer to one.",
  "Write one query with both clauses - a WHERE that cuts rows and a HAVING that cuts groups - and report how each changes the result.",
  "At the moment WHERE is evaluated, how many rows are in each group?",
  "Order the clauses by when the database evaluates them, not by how you typed them.",
  "The clauses run in a logical order: FROM, then WHERE on individual rows, then GROUP BY, then HAVING on the resulting groups, then SELECT, then ORDER BY. That is why an aggregate cannot appear in WHERE - it does not exist yet - and why every non-aggregated selected column must be in GROUP BY. Filtering early in WHERE is also usually faster, since fewer rows reach the grouping step.",
  "You need departments with more than five staff, counting only staff hired since 2020. Write which condition goes where and why.",
  [("lecture#db-w9-aggregates", "Week 9: answers must use the logical clause order to justify where a condition belongs."),
   ("lab#db-w9-brief", "Lab 9 brief: write one query that filters both rows and groups and explain each clause.")],
  ("lecture#db-w9-2019", "Archived note: WHERE and HAVING are interchangeable."),
  ["order", "aggregate", "group", "filter"]),

C("db_keys_integrity", "Database Systems", "keys and referential integrity",
  [("Says a primary key uniquely identifies a row", "the primary key is unique and not null for every row"),
   ("Says a foreign key references a key in another table", "the foreign key holds a value that must exist in the referenced table"),
   ("Says the constraint is enforced by the database", "the database rejects an insert or delete that would break the reference"),
   ("Names a delete behaviour", "you choose cascade, restrict or set null for what happens when the parent goes")],
  "that keys are documentation for the developer, so integrity can be maintained by being careful in application code",
  "We know which column links the tables, so declaring a foreign key is just extra work the application already handles.",
  ("Add a foreign key on order.customer_id, because every table should have foreign keys.",
   "the constraint belongs there, but the reason is the orphan rows you already have, not a blanket rule"),
  "A primary key identifies a row.",
  "Normalisation reduces redundancy.",
  "Declare the constraint in the schema and choose an explicit delete behaviour, so the invariant survives code you have not written yet.",
  "Application checks protect only the paths that run them; a database constraint holds for every path, including imports, scripts and the next developer.",
  "Count the orphan rows in your orders table, then add the constraint and record which inserts the database now rejects.",
  "Someone deletes a customer directly in the database console. What stops the orders pointing at nothing?",
  "List every route by which a row can be written. Ask which of them your application check covers.",
  "A primary key is a unique, non-null identifier; a foreign key says this value must exist over there, and the database enforces it on every write, not just the ones your code performs. That matters because imports, admin consoles, scripts and future code all bypass application checks. Declaring the constraint also forces a decision you otherwise make by accident: on delete cascade, restrict or set null - each of which is a different business rule.",
  "Deleting a student should keep their submitted work but detach it. Say which delete behaviour that is and what the column must allow.",
  [("lecture#db-w4-keys", "Week 4: integrity constraints belong in the schema; the assignment marks the declared delete behaviour."),
   ("lab#db-w4-brief", "Lab 4 brief: find the orphan rows in the supplied database, then prevent new ones.")],
  ("lecture#db-w4-2017", "Archived note: referential integrity is best enforced in application code."),
  ["constraint", "orphan", "cascade", "enforce"]),

C("db_sql_nosql", "Database Systems", "choosing between relational and document stores",
  [("Says relational stores enforce a schema and support joins", "a relational database checks structure and can join across tables"),
   ("Says document stores trade schema for flexibility", "a document store accepts varying shapes and nests related data"),
   ("Says the access pattern should drive the choice", "pick by how the data is queried, not by which is newer"),
   ("Says consistency guarantees differ and must be checked", "distributed stores may offer weaker consistency than a single relational node")],
  "that the choice is about scale or fashion, when it is about the shape of the queries and the guarantees you need",
  "We will use a document store because relational databases do not scale and everyone uses NoSQL now.",
  ("Keep the orders in a relational database, because money data needs ACID.",
   "the conclusion is defensible but stated as a slogan - the reason is the multi-table invariants your transactions must hold"),
  "SQL databases use tables.",
  "Indexes make reads faster.",
  "Write your three most frequent queries first, then choose the store whose natural access pattern serves them with the guarantees you need.",
  "Document stores are fast when the aggregate you read matches the document you wrote; the cost appears when you need relationships the document did not anticipate.",
  "Write your three most common queries, model them both ways, and count the round trips and duplicated fields each design needs.",
  "What are the three queries this system runs a hundred times a day?",
  "Start from the queries, not from the database. The queries usually choose for you.",
  "Relational stores give you a declared schema, joins and transactional invariants across tables. Document stores let you store a whole aggregate as one shape and read it in a single hit, at the price of duplicated data and application-side relationships. Scale is rarely the deciding factor at coursework or small-product size; access pattern is. Write the queries first: if they mostly fetch one aggregate by id, documents fit; if they cross entities and must stay mutually consistent, relational fits.",
  "Your app must show a student's profile in one request but also report on every enrolment by course. Propose a design and say what it duplicates.",
  [("lecture#db-w12-stores", "Week 12: store selection must be justified by access patterns and required guarantees."),
   ("lab#db-w12-brief", "Lab 12 brief: model the same domain relationally and as documents, and compare the two for three given queries.")],
  ("lecture#db-w12-2018", "Archived note: relational databases do not scale and should be avoided for new projects."),
  ["access pattern", "join", "aggregate", "guarantee"]),

]
